from .languages.deutsch import *
from .languages.english import *
from .languages.french import *
from .languages.italian import *
from .languages.japanese import *
from .languages.polish import *
from .languages.russian import *
from .languages.slovak import *
from .languages.slovenian import *
from .languages.spanish import *
from .languages.korean import *
from .languages.chinese import *
from .languages.czech import *